<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>name</key>
    <string>T4 Text Template</string>
    <key>scopeName</key>
    <string>text.tt</string>
    <key>fileTypes</key>
    <array>
      <string>t4</string>
      <string>tt</string>
      <string>ttinclude</string>
    </array>
    <key>patterns</key>
    <array>
      <dict>
        <key>begin</key>
        <string>(?&lt;!\\)(&lt;#@)\s*([_a-zA-Z0-9]*)</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.tag.begin.tt</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>entity.name.tag.tt</string>
          </dict>
        </dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>([_a-zA-Z0-9]+)(=)((")[^"]*("))</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>entity.other.attribute-name.tt</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>punctuation.separator.key-value.tt</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>string.quoted.double.tt</string>
              </dict>
              <key>4</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.string.begin.tt</string>
              </dict>
              <key>5</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.string.end.tt</string>
              </dict>
            </dict>
          </dict>
        </array>
        <key>end</key>
        <string>(?&lt;!\\)#&gt;</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.tag.end.tt</string>
          </dict>
        </dict>
      </dict>
      <dict>
        <key>begin</key>
        <string>(?&lt;!\\)&lt;#=</string>
        <key>beginCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.section.embedded.begin.tt</string>
          </dict>
        </dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>source.cs</string>
          </dict>
        </array>
        <key>end</key>
        <string>(?&lt;!\\)#&gt;</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.section.embedded.end.tt</string>
          </dict>
        </dict>
      </dict>
      <dict>
        <key>begin</key>
        <string>(?&lt;!\\)&lt;#\+</string>
        <key>beginCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.section.embedded.begin.tt</string>
          </dict>
        </dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>source.cs</string>
          </dict>
        </array>
        <key>end</key>
        <string>(?&lt;!\\)#&gt;</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.section.embedded.end.tt</string>
          </dict>
        </dict>
      </dict>
      <dict>
        <key>begin</key>
        <string>(?&lt;!\\)&lt;#</string>
        <key>beginCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.section.embedded.begin.tt</string>
          </dict>
        </dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>source.cs</string>
          </dict>
        </array>
        <key>end</key>
        <string>(?&lt;!\\)#&gt;</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.section.embedded.end.tt</string>
          </dict>
        </dict>
      </dict>
    </array>
  </dict>
</plist>